# Generated by Django 4.0 on 2021-12-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
