# Generated by Django 4.0 on 2021-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0002_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
