# Generated by Django 4.0 on 2021-12-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0003_remove_page_uuid_alter_page_follow_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='uuid',
            field=models.CharField(default=11, max_length=30, unique=True),
        ),
    ]
