# Generated by Django 4.0 on 2021-12-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0004_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
