# Generated by Django 3.2.9 on 2021-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0002_alter_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
